### ALBERT MONTILLA
### VARIABLE OBJETIVO P1: CREACION DE LA BASE FINAL MORA CON PRIMERA FECHA MORA 30, 60, 90 DIAS

In [11]:
import pandas as pd
from datetime import datetime
pd.set_option('display.max_columns', 500)
import math
import matplotlib.pyplot as plt
import numpy as np

In [19]:
Base_Independientes = pd.read_excel('../data/raw/Base_Independientes.xlsx')

In [20]:
Base_Independientes.SECTOR1 = Base_Independientes.SECTOR1.str.upper()
Base_Independientes[Base_Independientes['cartera'] == 'activo']['SECTOR1'].value_counts()

TDC                     181427
HIPOTECA RESIDENCIAL     34614
CONSUMO PERSONAL         33728
AUTO                     13558
Name: SECTOR1, dtype: int64

In [21]:
date_format = '%Y%m%d'
Base_Independientes['FECHA'] = Base_Independientes.FECHA.apply(lambda x: datetime.strptime(str(x),date_format))
Base_Independientes['FECHA_INICIO'] = Base_Independientes.FECHA_INICIO.apply(lambda x: datetime.strptime(str(x),date_format))

In [22]:
filtro = (Base_Independientes['SECTOR1'] == 'TDC') |  (Base_Independientes['SECTOR1'] == 'HIPOTECA RESIDENCIAL') | (Base_Independientes['SECTOR1'] == 'CONSUMO PERSONAL')| (Base_Independientes['SECTOR1'] == 'AUTO')

In [23]:
Base_Independientes_f = Base_Independientes[filtro]
Base_Independientes_f = Base_Independientes_f.reset_index(drop=True)

In [24]:
Base_Independientes_f['MADUREZ'] = Base_Independientes_f['FECHA'] - Base_Independientes_f['FECHA_INICIO']
Base_Independientes_f['MADUREZ'] = Base_Independientes_f['MADUREZ'].apply(lambda x: math.ceil(x.days/30))

In [25]:
Base_Independientes_f['MADUREZ']

0          91
1          90
2          90
3           1
4           1
5           1
6           1
7           1
8           1
9           1
10          1
11          1
12         11
13         11
14         54
15          5
16          4
17         55
18         65
19         70
20         71
21          4
22          4
23         22
24         22
25        131
26          8
27         13
28         28
29          8
         ...
263297     35
263298     81
263299     75
263300     15
263301     81
263302     24
263303      5
263304      5
263305      5
263306      5
263307      5
263308      5
263309    111
263310    110
263311    110
263312     43
263313     42
263314     40
263315     38
263316     37
263317     36
263318     36
263319     33
263320     32
263321     30
263322     30
263323     28
263324     23
263325     11
263326     23
Name: MADUREZ, Length: 263327, dtype: int64

In [26]:
Base_Independientes_f.head()

,FECHA,CLIENTE,SECTOR1,SECTOR4,SALDO,FECHA_INICIO,FECHA_VENCIMIENTO,DIAS_MORA,RANGO_MORA,PROXIMO_PAGO_CAPITAL,PROXIMO_PAGO_INTERES,fecha_reestructurado,clasificacion_Regulatoria,MONTO_IN,CUOTA_XPAGAR,ingreso,segmento,cartera,max_mora_ult_12M,Descripcion_Nivel_Educacion,Estadocivil,Genero,cantidad_Dependientes,Cargo,DescripcionIndustria,DescripcionSector,Nacionalidad,Residencia,TiempoRelacionBanco,CLASIFICACION_4,CLASIFICACION_5,SubTipoCliente,FechaNacimiento,Imgreso_DIMCLIENTES,IngresoMensual,FechaEmpleoActual,pais,provincia,ciudad,Fecha_Ult_pago_Interes,Fecha_Ult_pago_Capital,Monto_Ult_pago_Interes,Monto_Ult_pago_Capital,categoria_cambio,DESC_ESTADO_TARJETA_t,Operacion_codificada,MADUREZ
0,2022-02-28,600127517,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,71103.62,2014-09-25,20440903.0,0.0,1. Al día,20220303.0,20220303.0,NaN,1.0,80410.0,389.94,0.0,NaN,activo,NaN,Universitario,MARRIED,MALE,0,ABOGADO,LEGAL,P Natural,PA,PA,9Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19740108,2530.83,2530.83,20050301,PANAMA,PANAMA,PANAMA,20220210,20220210,321.70,19.50,NaN,NaN,3030XXXX5646,91
1,2022-02-28,600086511,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,97427.19,2014-10-21,20441003.0,0.0,1. Al día,20220303.0,20220303.0,20210602.0,3.0,106500.0,498.58,0.0,NaN,activo,NaN,Maestría,MARRIED,MALE,0,-,CONSTRUCCION,P Natural,PA,PA,11Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19820901,5000.00,5000.00,20151101,PANAMA,PANAMA,PANAMA,20200317,20201126,304.79,332.93,3.0,NaN,3030XXXX6075,90
2,2022-02-28,600114703,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,65146.81,2014-10-30,20441003.0,0.0,1. Al día,20220303.0,20220303.0,NaN,1.0,73000.0,199.73,0.0,NaN,activo,NaN,Universitario,SINGLE,FEMALE,0,-,ROPA CALZADO Y ACCESORIOS,P Natural,PA,PA,22Y,COMERCIALES,INDEPENDIENTES,Cliente Regular,19790620,2000.00,2000.00,20090301,PANAMA,CHIRIQUI,DAVID,20220203,20220203,144.99,18.16,NaN,NaN,3030XXXX6155,90
3,2022-03-31,990052433,HIPOTECA RESIDENCIAL,Hipoteca No Preferencial,300800.00,2022-03-18,20520403.0,0.0,1. Al día,20220503.0,20220503.0,NaN,1.0,300800.0,777.27,0.0,NaN,activo,NaN,Doctorado,MARRIED,MALE,0,ADMINISTRADOR,ALIMENTOS,P Natural,VE,PA,1Y,COMERCIALES,INDEPENDIENTES,Cliente Regular,19760906,5735.00,5735.00,20191204,PANAMA,PANAMA,Panama,NaN,NaN,0.00,0.00,NaN,NaN,1021XXX807,1
4,2022-03-31,600044329,CONSUMO PERSONAL,PP Prendarios,52202.00,2022-03-19,20270319.0,0.0,1. Al día,20270319.0,20220419.0,NaN,1.0,52202.0,52202.00,0.0,NaN,activo,NaN,Doctorado,MARRIED,FEMALE,1,ABOGADO,INSTITUCIONES DE GOBIERNO,P Natural,PA,PA,22Y,OTROS,INDEPENDIENTES,Cliente Regular,19770613,14113.75,14113.75,20191023,PANAMA,PANAMA,Panama,NaN,NaN,0.00,0.00,NaN,NaN,1021XXX567,1

In [27]:
len(Base_Independientes_f)

263327

In [28]:
len(Base_Independientes_f.CLIENTE.unique())

4896

In [29]:
Base_Independientes_f.categoria_cambio.value_counts()

3.0    52169
2.0     5870
1.0     1667
Name: categoria_cambio, dtype: int64

In [30]:
Base_Independientes_f[Base_Independientes_f.CLIENTE ==600007221].sort_values('FECHA')

,FECHA,CLIENTE,SECTOR1,SECTOR4,SALDO,FECHA_INICIO,FECHA_VENCIMIENTO,DIAS_MORA,RANGO_MORA,PROXIMO_PAGO_CAPITAL,PROXIMO_PAGO_INTERES,fecha_reestructurado,clasificacion_Regulatoria,MONTO_IN,CUOTA_XPAGAR,ingreso,segmento,cartera,max_mora_ult_12M,Descripcion_Nivel_Educacion,Estadocivil,Genero,cantidad_Dependientes,Cargo,DescripcionIndustria,DescripcionSector,Nacionalidad,Residencia,TiempoRelacionBanco,CLASIFICACION_4,CLASIFICACION_5,SubTipoCliente,FechaNacimiento,Imgreso_DIMCLIENTES,IngresoMensual,FechaEmpleoActual,pais,provincia,ciudad,Fecha_Ult_pago_Interes,Fecha_Ult_pago_Capital,Monto_Ult_pago_Interes,Monto_Ult_pago_Capital,categoria_cambio,DESC_ESTADO_TARJETA_t,Operacion_codificada,MADUREZ
156484,2017-01-31,600007221,TDC,TARJETAS,1015.30,2007-12-13,20191231.0,0.0,1. Al Día,20191231.0,20191231.0,NaN,1.0,1000.00,21.34,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,112
145791,2017-02-28,600007221,TDC,TARJETAS,1039.32,2007-12-13,20191231.0,0.0,1. Al día,20191231.0,20191231.0,NaN,1.0,1000.00,20.84,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,113
142510,2017-03-31,600007221,TDC,TARJETAS,986.81,2007-12-13,20191231.0,0.0,1. Al Día,20191231.0,20191231.0,NaN,1.0,1000.00,22.13,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,114
143034,2017-04-30,600007221,TDC,TDC,972.86,2007-12-13,20191231.0,0.0,NaN,20191231.0,20191231.0,NaN,1.0,1000.00,20.23,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,115
10484,2017-05-31,600007221,TDC,TDC,970.06,2007-12-13,20191231.0,0.0,1. Al Día,20191231.0,20191231.0,NaN,1.0,1000.00,19.92,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,116
11990,2017-06-30,600007221,TDC,TDC,953.89,2007-12-13,20191231.0,0.0,1. Al Día,20191231.0,20191231.0,NaN,1.0,1000.00,19.87,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,117
86266,2017-07-31,600007221,TDC,TDC,986.90,2007-12-13,20191231.0,0.0,1. Al Día,20191231.0,20191231.0,NaN,1.0,1000.00,19.80,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,118
247157,2017-07-31,600007221,TDC,TDC,509.72,2017-06-24,20210630.0,0.0,1. Al Día,20210630.0,20210630.0,NaN,1.0,1000.00,0.08,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,2
221496,2017-08-31,600007221,TDC,TDC,967.83,2007-12-13,20191231.0,0.0,1. Al Día,20191231.0,20191231.0,NaN,1.0,1000.00,20.35,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,119
40656,2017-08-31,600007221,TDC,TDC,939.00,2017-06-24,20210630.0,0.0,1. Al Día,20210630.0,20210630.0,NaN,1.0,1000.00,14.95,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,3
143920,2017-09-30,600007221,TDC,TDC,1004.25,2007-12-13,20191231.0,0.0,1,20191231.0,20191231.0,NaN,1.0,1000.00,19.83,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,120
251367,2017-09-30,600007221,TDC,TDC,975.97,2017-06-24,20210630.0,0.0,1,20210630.0,20210630.0,NaN,1.0,1000.00,19.32,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,4
187881,2017-10-31,600007221,TDC,TDC,1015.12,2007-12-13,20191231.0,0.0,1. Al Día,20191231.0,20191231.0,NaN,1.0,1000.00,1015.12,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,121
30445,2017-10-31,600007221,TDC,TDC,996.28,2017-06-24,20210630.0,0.0,1. Al Día,20210630.0,20210630.0,NaN,1.0,1000.00,996.28,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,5
144085,2017-11-30,600007221,TDC,TDC,923.25,2017-06-24,20210630.0,0.0,1. Al Día,20171201.0,20171201.0,NaN,1.0,1000.00,20.46,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,6
1899,2017-11-30,600007221,TDC,TDC,944.81,2007-12-13,20191231.0,0.0,1. Al Día,20171211.0,20171211.0,NaN,1.0,1000.00,20.89,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,122
60777,2017-12-31,600007221,TDC,TDC,1032.98,2007-12-13,20191231.0,0.0,1. Al Día,20180110.0,20180110.0,NaN,1.0,1000.00,21.49,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,123
243643,2017-12-31,600007221,TDC,TDC,961.43,2017-06-24,20210630.0,0.0,1. Al Día,20180102.0,20180102.0,NaN,1.0,1000.00,19.29,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,7
244316,2018-01-31,600007221,TDC,TDC,1006.43,2007-12-13,20191231.0,0.0,1. Al Día,20180212.0,20180212.0,NaN,1.0,1000.00,19.61,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,124
181597,2018-01-31,600007221,TDC,TDC,938.30,2017-06-24,20210630.0,0.0,1. Al Día,20180201.0,20180201.0,NaN,1.0,1000.00,18.56,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,8
61246,2018-02-28,600007221,TDC,TDC,984.52,2017-06-24,20210630.0,0.0,1. Al Día,20180301.0,20180301.0,NaN,1.0,1000.00,19.29,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,9
172685,2018-02-28,600007221,TDC,TDC,1001.29,2007-12-13,20191231.0,0.0,1. Al Día,20180312.0,20180312.0,NaN,1.0,1500.00,20.02,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,125
116869,2018-03-31,600007221,TDC,TDC,897.81,2017-06-24,20210630.0,0.0,1. Al Día,20180402.0,20180402.0,NaN,1.0,1000.00,39.24,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,10
114338,2018-03-31,600007221,TDC,TDC,1411.00,2007-12-13,20191231.0,0.0,1. Al Día,20180410.0,20180410.0,NaN,1.0,1009.62,37.64,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,126
230472,2018-04-30,600007221,TDC,TDC,893.82,2017-06-24,20210630.0,0.0,1. Al Día,20180502.0,20180502.0,NaN,1.0,1000.00,893.82,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,11
61543,2018-04-30,600007221,TDC,TDC,1412.07,2007-12-13,20191231.0,0.0,1. Al Día,20180510.0,20180510.0,NaN,1.0,1019.43,1412.07,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,127
258955,2018-05-31,600007221,TDC,TDC,1407.68,2007-12-13,20191231.0,0.0,1. Al Día,20180611.0,20180611.0,NaN,1.0,1029.44,35.61,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,128
188462,2018-05-31,600007221,TDC,TDC,899.00,2017-06-24,20210630.0,0.0,1. Al Día,20180601.0,20180601.0,NaN,1.0,1000.00,15.34,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,12
186316,2018-06-30,600007221,TDC,TDC,1444.03,2007-12-13,20191231.0,0.0,1. Al Día,20180710.0,20180710.0,NaN,1.0,1039.65,35.71,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,4466XXXXXXXX7008,129
34201,2018-06-30,600007221,TDC,TDC,983.57,2017-06-24,20210630.0,0.0,1. Al Día,20180702.0,20180702.0,NaN,1.0,1000.00,16.42,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,NaN,NaN,NaN,ACTIVA,5436XXXXXXXX3002,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134178,2021-09-30,600007221,TDC,TDC,3117.86,2017-06-24,NaN,0.0,1. Al día,20211012.0,20211012.0,20200827.0,4.0,1700.00,191.06,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,35.79,29.21,3.0,NaN,5436XXXXXXXX3002,52
11876,2021-10-31,600007221,TDC,TDC,3271.93,2017-06-24,NaN,0.0,1. Al día,20211112.0,20211112.0,20211027.0,3.0,1700.00,191.06,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,35.79,29.21,3.0,NaN,5436XXXXXXXX3002,53
78723,2021-10-31,600007221,TDC,TDC,2285.40,2007-12-13,NaN,0.0,1. Al día,20211112.0,20211112.0,20211027.0,3.0,1300.00,907.40,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,29.38,30.62,3.0,NaN,4466XXXXXXXX7008,170
8373,2021-10-31,600007221,TDC,TDC,173.55,2021-05-17,20230617.0,0.0,1. Al día,20211112.0,20211112.0,20210517.0,1.0,214.30,9.14,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20211017,20211017,0.91,8.23,3.0,NaN,5436XXXXXXXX6900,6
220803,2021-11-30,600007221,TDC,TDC,3343.01,2017-06-24,NaN,0.0,1. Al día,20211213.0,20211213.0,20211027.0,3.0,1700.00,1671.40,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,35.79,29.21,3.0,NaN,5436XXXXXXXX3002,54
217834,2021-11-30,600007221,TDC,TDC,165.28,2021-05-17,20230617.0,0.0,1. Al día,20211213.0,20211213.0,20210517.0,1.0,214.30,9.14,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20211117,20211117,0.87,8.27,3.0,NaN,5436XXXXXXXX6900,7
51191,2021-11-30,600007221,TDC,TDC,2325.45,2007-12-13,NaN,0.0,1. Al día,20211213.0,20211213.0,20211027.0,3.0,1300.00,1047.16,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,29.38,30.62,3.0,NaN,4466XXXXXXXX7008,171
31720,2021-12-31,600007221,TDC,TDC,2379.09,2007-12-13,NaN,0.0,1. Al día,20220112.0,20220112.0,20211027.0,3.0,1300.00,1122.15,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,29.38,30.62,3.0,NaN,4466XXXXXXXX7008,172
51409,2021-12-31,600007221,TDC,TDC,3426.53,2017-06-24,NaN,0.0,1. Al día,20220112.0,20220112.0,20211027.0,3.0,1700.00,57.22,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,35.79,29.21,3.0,NaN,5436XXXXXXXX3002,56
110742,2021-12-31,600007221,TDC,TDC,156.97,2021-05-17,20230617.0,0.0,1. Al día,20220112.0,20220112.0,20211027.0,3.0,214.30,9.14,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20211217,20211217,0.83,8.31,3.0,NaN,5436XXXXXXXX6900,8
135218,2022-01-31,600007221,TDC,TDC,3525.53,2017-06-24,NaN,0.0,1. Al día,20220512.0,20220512.0,20211027.0,3.0,1700.00,58.88,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,35.79,29.21,3.0,NaN,5436XXXXXXXX3002,57
54598,2022-01-31,600007221,TDC,TDC,148.61,2021-05-17,20230617.0,0.0,1. Al día,20220212.0,20220212.0,20211027.0,3.0,214.30,9.14,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20220117,20220117,0.78,8.36,3.0,NaN,5436XXXXXXXX6900,9
235132,2022-01-31,600007221,TDC,TDC,2416.98,2007-12-13,NaN,20.0,2. Hasta 30 días,20220212.0,20220212.0,20211027.0,3.0,1300.00,1181.03,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,29.38,30.62,3.0,NaN,4466XXXXXXXX7008,173
5403,2022-02-28,600007221,TDC,TDC,3624.74,2017-06-24,NaN,0.0,1. Al día,20220512.0,20220512.0,20211027.0,3.0,1700.00,60.53,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,35.79,29.21,3.0,NaN,5436XXXXXXXX3002,57
711,2022-02-28,600007221,TDC,TDC,140.21,2021-05-17,20230617.0,0.0,1. Al día,20220312.0,20220312.0,20211027.0,3.0,214.30,9.14,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20220217,20220217,0.74,8.40,3.0,NaN,5436XXXXXXXX6900,10
153512,2022-02-28,600007221,TDC,TDC,2474.08,2007-12-13,NaN,48.0,3. Hasta 60 días,20220312.0,20220312.0,20211027.0,4.0,1300.00,1258.77,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,29.38,30.62,3.0,NaN,4466XXXXXXXX7008,174
212287,2022-03-31,600007221,TDC,TDC,131.77,2021-05-17,20230617.0,0.0,1. Al día,20220512.0,20220512.0,20211027.0,3.0,214.30,9.14,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20220317,20220317,0.70,8.44,3.0,NaN,5436XXXXXXXX6900,11
216164,2022-03-31,600007221,TDC,TDC,3716.89,2017-06-24,NaN,0.0,1. Al día,20220512.0,20220512.0,20211027.0,3.0,1700.00,62.07,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,35.79,29.21,3.0,NaN,5436XXXXXXXX3002,59
52199,2022-03-31,600007221,TDC,TDC,2526.55,2007-12-13,NaN,79.0,4. Hasta 90 días,20220412.0,20220412.0,20211027.0,4.0,1300.00,1331.54,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,29.38,30.62,3.0,NaN,4466XXXXXXXX7008,175
205070,2022-04-30,600007221,TDC,TDC,2534.33,2007-12-13,NaN,109.0,5. Hasta 120 días,20220512.0,20220512.0,20211027.0,5.0,1300.00,1359.27,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,29.38,30.62,3.0,NaN,4466XXXXXXXX7008,176
52489,2022-04-30,600007221,TDC,TDC,3998.91,2022-04-16,20320417.0,0.0,1. Al día,20220512.0,20220512.0,NaN,1.0,3998.91,93.38,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,NaN,NaN,0.00,0.00,NaN,NaN,5436XXXXXXXX6662,1
80527,2022-05-31,600007221,TDC,TDC,2542.11,2007-12-13,NaN,140.0,6. Hasta 180 días,20220613.0,20220613.0,20211027.0,5.0,1300.00,1386.68,0.0,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,ADMINISTRACION,P Natural,NI,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19671114,1000.0,1000.0,20030502,PANAMA,PANAMA OESTE,LA CHORRERA,20191129,20191129,29.38,30.62,2.0,NaN,4466XXXXXXXX7008,177

In [31]:
Base_Independientes_f[Base_Independientes_f.fecha_reestructurado.notnull()]

,FECHA,CLIENTE,SECTOR1,SECTOR4,SALDO,FECHA_INICIO,FECHA_VENCIMIENTO,DIAS_MORA,RANGO_MORA,PROXIMO_PAGO_CAPITAL,PROXIMO_PAGO_INTERES,fecha_reestructurado,clasificacion_Regulatoria,MONTO_IN,CUOTA_XPAGAR,ingreso,segmento,cartera,max_mora_ult_12M,Descripcion_Nivel_Educacion,Estadocivil,Genero,cantidad_Dependientes,Cargo,DescripcionIndustria,DescripcionSector,Nacionalidad,Residencia,TiempoRelacionBanco,CLASIFICACION_4,CLASIFICACION_5,SubTipoCliente,FechaNacimiento,Imgreso_DIMCLIENTES,IngresoMensual,FechaEmpleoActual,pais,provincia,ciudad,Fecha_Ult_pago_Interes,Fecha_Ult_pago_Capital,Monto_Ult_pago_Interes,Monto_Ult_pago_Capital,categoria_cambio,DESC_ESTADO_TARJETA_t,Operacion_codificada,MADUREZ
1,2022-02-28,600086511,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,97427.19,2014-10-21,20441003.0,0.0,1. Al día,20220303.0,20220303.0,20210602.0,3.0,106500.00,498.58,0.0,NaN,activo,NaN,Maestría,MARRIED,MALE,0,-,CONSTRUCCION,P Natural,PA,PA,11Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19820901,5000.00,5000.00,20151101,PANAMA,PANAMA,PANAMA,20200317,20201126,304.79,332.93,3.0,NaN,3030XXXX6075,90
20,2022-03-31,600194073,TDC,TDC,1380.95,2016-06-21,NaN,20.0,2. Hasta 30 días,20220412.0,20220412.0,20211027.0,3.0,29589.16,1229.24,0.0,NaN,activo,NaN,Universitario,MARRIED,MALE,0,-,ADMINISTRACION,P Natural,PA,PA,6Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19740219,3000.00,3000.00,20120505,PANAMA,PANAMA OESTE,ARRAIJAN,20200304,20200304,32.33,977.67,3.0,NaN,5161XXXXXXXX8000,71
23,2022-05-31,600156551,CONSUMO PERSONAL,PP Readecuación de Préstamo,8196.64,2020-08-25,20280203.0,0.0,1. Al día,20220603.0,20220603.0,20200825.0,1.0,9390.00,183.48,0.0,NaN,activo,NaN,Universitario,MARRIED,FEMALE,2,-,ADMINISTRACION,P Natural,PA,PA,8Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19770423,1108.00,1108.00,20170403,PANAMA,PANAMA,PANAMA,20220503,20220503,72.58,98.07,2.0,NaN,1020XXX379,22
40,2017-02-28,600016275,HIPOTECA RESIDENCIAL,VIVIENDA USADA,38954.96,2009-03-09,20390403.0,117.0,5. Hasta 120 días,20170303.0,20170303.0,20160629.0,2.0,41650.00,248.82,NaN,NaN,activo,NaN,Universitario,SINGLE,MALE,0,CONTRATISTA,CONSTRUCCION,P Natural,PA,PA,14Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19651114,1500.00,1500.00,20080601,PANAMA,COLON,COLON,NaN,NaN,NaN,NaN,NaN,NaN,3040XXXX2911,98
62,2017-09-30,600112469,HIPOTECA RESIDENCIAL,Hipoteca Pref - Hasta $120,69069.18,2013-02-18,20430203.0,89.0,1,20171003.0,20171003.0,20160629.0,2.0,73871.80,345.10,NaN,NaN,activo,NaN,Universitario,SINGLE,FEMALE,1,-,ARQUITECTURA Y URBANISMO,P Natural,PA,PA,10Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19810807,3000.00,3000.00,20100101,PANAMA,PANAMA,PANAMA,NaN,NaN,NaN,NaN,NaN,NaN,3030XXXX3613,57
124,2022-07-31,600203459,CONSUMO PERSONAL,PP Readecuación de Préstamo,7771.66,2022-05-30,20350228.0,0.0,1. Al día,20220803.0,20220803.0,20220530.0,3.0,7800.00,87.95,0.0,NaN,activo,NaN,Universitario,SINGLE,FEMALE,0,-,ADMINISTRACION,P Natural,PA,PA,6Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19720311,800.00,800.00,20111201,PANAMA,CHIRIQUI,PANAMA,20220711,20220711,19.62,28.34,3.0,NaN,1021XXX795,3
186,2018-08-31,600112394,HIPOTECA RESIDENCIAL,Traspaso de Hipoteca,65111.77,2013-06-07,20430703.0,28.0,2. Hasta 30 Días,20180903.0,20180903.0,20160528.0,1.0,69817.90,368.13,2250.0,MASIVO LOCAL,activo,NaN,Universitario,MARRIED,MALE,1,GERENTE SUB GERENTE,CONSTRUCCION,P Natural,PA,PA,10Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19710429,2250.00,2250.00,20120101,PANAMA,PANAMA,PANAMA,NaN,NaN,NaN,NaN,NaN,NaN,3040XXXX9583,64
242,2017-12-31,600112394,HIPOTECA RESIDENCIAL,Traspaso de Hipoteca,65741.86,2013-06-07,20430703.0,28.0,2. Hasta 30 Días,20180103.0,20180103.0,20160528.0,2.0,69817.90,368.13,NaN,NaN,activo,NaN,Universitario,MARRIED,MALE,1,GERENTE SUB GERENTE,CONSTRUCCION,P Natural,PA,PA,10Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19710429,2250.00,2250.00,20120101,PANAMA,PANAMA,PANAMA,NaN,NaN,NaN,NaN,NaN,NaN,3040XXXX9583,56
380,2019-01-31,600112469,HIPOTECA RESIDENCIAL,Hipoteca Pref - Hasta $120,68738.50,2013-02-18,20430203.0,0.0,1. Al Día,20190203.0,20190203.0,20181219.0,2.0,73871.80,345.10,3000.0,MASIVO LOCAL,activo,NaN,Universitario,SINGLE,FEMALE,1,-,ARQUITECTURA Y URBANISMO,P Natural,PA,PA,10Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19810807,3000.00,3000.00,20100101,PANAMA,PANAMA,PANAMA,20190130,20190130,55.05,123.33,NaN,NaN,3030XXXX3613,73
385,2019-02-28,600017595,HIPOTECA RESIDENCIAL,Hipoteca Pref - Hasta $65,40308.72,2009-06-09,20390703.0,0.0,1. Al Día,20190303.0,20190303.0,20180823.0,1.0,53100.00,202.97,0.0,MASIVO LOCAL,activo,NaN,Universitario,MARRIED,MALE,1,-,TECNOLOGIA DE INFORMACION,P Natural,PA,PA,14Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19681020,850.00,850.00,19000101,PANAMA,PANAMA,Panama,20190207,20190207,75.82,126.80,NaN,NaN,3030XXXX3582,119
471,2019-09-30,600193322,CONSUMO PERSONAL,PP Readecuación de Préstamo,21789.00,2019-04-27,20340503.0,58.0,3. Hasta 60 días,20191003.0,20191003.0,20190427.0,4.0,22700.00,90.21,4000.0,LOCAL RETAIL?MA,activo,NaN,Universitario,MARRIED,MALE,0,-,DISENO Y DECORACION,P Natural,VE,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19870612,4000.00,4000.00,20131001,PANAMA,PANAMA OESTE,PANAMA,20190930,20190930,145.85,88.22,NaN,NaN,3230XXXX0112,6
478,2019-10-31,600057766,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,55280.69,2014-05-19,20440603.0,0.0,1. Al día,20191103.0,20191103.0,20181122.0,1.0,63700.00,150.64,NaN,NaN,activo,NaN,Secundaria,MARRIED,FEMALE,0,-,BANCOS,P Natural,PA,PA,12Y,FINANZAS Y SEGUROS,INDEPENDIENTES,Cliente Regular,19811130,1200.00,1200.00,20161015,PANAMA,PANAMA,Panama,20191003,20191003,80.84,153.10,NaN,NaN,3030XXXX2809,67
488,2019-11-30,600070104,TDC,TDC,2456.14,2015-03-20,20200331.0,74.0,4. Hasta 90 días,20191212.0,20191212.0,20190719.0,2.0,3960.00,219.68,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,0,-,CONSTRUCCION,P Natural,PA,PA,12Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19710429,1623.16,1623.16,20080101,PANAMA,PANAMA,PANAMA,NaN,20190715,0.00,54.92,NaN,ARREGLO DE PAGO,4466XXXXXXXX4011,58
532,2020-04-30,600018666,TDC,TDC,4028.73,2018-07-19,20220731.0,0.0,1. Al día,20200512.0,20200512.0,20200330.0,1.0,3800.00,456.46,NaN,NaN,activo,NaN,Universitario,MARRIED,FEMALE,0,-,ADMINISTRACION,P Natural,VE,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19770120,5000.00,5000.00,20180901,PANAMA,PANAMA,Panama,20200318,20200318,5.60,60.00,3.0,SOBREGIRADA,4466XXXXXXXX7000,22
534,2020-04-30,600114372,TDC,TDC,12047.46,2014-05-14,20210531.0,0.0,1. Al día,20200512.0,20200512.0,20200331.0,1.0,13337.70,12047.46,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,0,GANADERO,TRANSPORTE TERRESTRE,P Natural,PA,PA,9Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19860329,3146.82,3146.82,19950225,PANAMA,PANAMA,CHEPO,20200312,20200312,127.75,288.78,3.0,ACTIVA,4466XXXXXXXX5016,73
535,2020-04-30,600223768,TDC,TDC,22933.91,2017-09-15,20201231.0,0.0,1. Al día,20200512.0,20200512.0,20200331.0,2.0,15000.00,458.78,NaN,NaN,activo,NaN,Universitario,SINGLE,FEMALE,0,-,ARTE,P Natural,PA,PA,5Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19730706,2000.00,2000.00,20020101,PANAMA,PANAMA,SAN MIGUELITO,20200312,20200312,165.55,296.45,3.0,ARREGLO DE PAGO,5536XXXXXXXX0006,32
536,2020-04-30,600217493,TDC,TDC,18500.65,2017-05-30,20210531.0,0.0,1. Al día,20200512.0,20200512.0,20200331.0,1.0,23500.00,18500.65,NaN,NaN,activo,NaN,Secundaria,SINGLE,MALE,0,-,SERVICIO DE CONSULTORIA,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19520527,1700.00,1700.00,19780216,PANAMA,PANAMA,PANAMA,20200228,20200228,56.59,743.41,3.0,ACTIVA,5536XXXXXXXX4008,36
538,2020-04-30,600227072,TDC,TDC,14008.12,2017-12-21,20211231.0,284.0,7. Hasta 1 año,20200512.0,20200512.0,20190525.0,5.0,12500.00,3330.53,NaN,NaN,activo,NaN,Universitario,MARRIED,MALE,0,-,ASESORIA Y ASISTENCIA,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19700920,8000.00,8000.00,20140101,PANAMA,PANAMA,PANAMA,20190517,20190517,296.36,233.64,2.0,EN MONITOREO,5536XXXXXXXX0003,29
539,2020-04-30,600013503,TDC,TDC,21011.79,2017-10-30,20211031.0,0.0,1. Al día,20200512.0,20200512.0,20200330.0,1.0,23000.00,21011.79,NaN,NaN,activo,NaN,Universitario,MARRIED,FEMALE,1,-,LEGAL,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19770112,10000.00,10000.00,20010401,PANAMA,PANAMA,PANAMA,20200227,20200227,97.86,702.14,3.0,ACTIVA,5536XXXXXXXX0008,31
540,2020-04-30,600066366,TDC,TDC,17296.68,2018-01-10,20210131.0,0.0,1. Al día,20200512.0,20200512.0,20200331.0,1.0,17500.00,17296.68,NaN,NaN,activo,NaN,Universitario,MARRIED,MALE,0,-,CONSTRUCCION,P Natural,VE,PA,22Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19651105,8300.00,8300.00,20100916,PANAMA,PANAMA,Panama,20200429,20200401,90.00,100.00,3.0,ACTIVA,5536XXXXXXXX0002,29
544,2020-04-30,600198826,TDC,TDC,17228.04,2017-09-27,20210930.0,0.0,1. Al día,20200512.0,20200512.0,20200331.0,1.0,12125.00,5421.58,NaN,NaN,activo,NaN,Maestría,MARRIED,MALE,0,-,ADMINISTRACION,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19781103,4800.00,4800.00,20070301,PANAMA,PANAMA,PANAMA,20200317,20200316,270.00,142.79,3.0,MOROSIDAD,5536XXXXXXXX8005,32
545,2020-04-30,600226747,TDC,TDC,13596.59,2017-10-30,20211031.0,0.0,1. Al día,20200512.0,20200512.0,20200331.0,1.0,16975.00,13596.59,NaN,NaN,activo,NaN,Universitario,SINGLE,FEMALE,0,-,RESTAURANTES Y SERVICIOS,P Natural,PA,PA,5Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19480322,2500.00,2500.00,20111201,PANAMA,PANAMA,SAN MIGUELITO,20200302,20200302,10.44,319.56,3.0,ACTIVA,5536XXXXXXXX3002,31
546,2020-04-30,600210713,TDC,TDC,28527.61,2017-09-06,20210930.0,0.0,1. Al día,20200512.0,20200512.0,20200327.0,1.0,27853.53,28527.61,NaN,NaN,activo,NaN,Universitario,SINGLE,MALE,0,-,ADMINISTRACION,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19910106,2800.00,2800.00,20140401,PANAMA,CHIRIQUI,DAVID,20200316,20200318,24.93,62.30,3.0,SOBREGIRADA,5536XXXXXXXX5016,33
547,2020-04-30,600209346,TDC,TDC,3709.06,2018-07-17,20210731.0,0.0,1. Al día,20200512.0,20200512.0,20200327.0,1.0,3750.00,138.41,NaN,NaN,activo,NaN,Universitario,SINGLE,MALE,0,-,ADMINISTRACION,P Natural,PA,PA,5Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19890724,1500.00,1500.00,20141201,PANAMA,PANAMA,Panama,20200323,20200323,51.04,11.96,3.0,ARREGLO DE PAGO,5536XXXXXXXX7005,22
548,2020-04-30,600191766,TDC,TDC,12480.93,2017-07-06,20210731.0,0.0,1. Al día,20200512.0,20200512.0,20200331.0,1.0,12500.00,12480.93,NaN,NaN,activo,NaN,Universitario,SINGLE,FEMALE,0,-,ADMINISTRACION,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19701002,5000.00,5000.00,20010301,PANAMA,PANAMA,PANAMA,20200320,20200320,36.87,266.59,3.0,ACTIVA,5536XXXXXXXX4000,35
549,2020-04-30,600042474,TDC,TDC,10399.45,2018-08-08,20210731.0,0.0,1. Al día,20200512.0,20200512.0,20200331.0,1.0,10000.00,10399.45,NaN,NaN,activo,NaN,Secundaria,SINGLE,FEMALE,0,FABRICANTE PROPIETARIO,TRANSPORTE TERRESTRE,P Natural,PA,PA,13Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19590331,1068.17,1068.17,20020501,PANAMA,CHIRIQUI,DAVID,20200302,20200302,133.06,216.94,3.0,SOBREGIRADA,5536XXXXXXXX3000,22
550,2020-04-30,600190739,TDC,TDC,9093.31,2017-06-30,20210630.0,0.0,1. Al día,20200512.0,20200512.0,20200331.0,1.0,25000.00,9093.31,NaN,NaN,activo,NaN,Universitario,MARRIED,MALE,0,-,ADMINISTRACION,P Natural,PA,PA,6Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19630325,1093.33,1093.33,20000201,PANAMA,PANAMA OESTE,Panama,20200227,20200227,2.10,219.90,3.0,ACTIVA,5536XXXXXXXX6000,35
551,2020-04-30,600237706,TDC,TDC,24890.97,2019-02-02,20220228.0,0.0,1. Al día,20200512.0,20200512.0,20200327.0,1.0,24300.00,24890.97,NaN,NaN,activo,NaN,Universitario,SINGLE,MALE,0,PRESIDENTE,ADMINISTRACION,P Natural,VE,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19800424,12669.62,12669.62,20160601,PANAMA,PANAMA,Panama,20200318,20200404,70.00,20.00,3.0,ACTIVA,5536XXXXXXXX7008,16
553,2020-05-31,600193439,TDC,TDC,965.45,2016-09-21,20210930.0,0.0,1. Al día,20200612.0,20200612.0,20200331.0,1.0,2300.00,965.45,NaN,NaN,activo,NaN,Maestría,MARRIED,MALE,0,-,MERCANCIA,P Natural,CO,PA,6Y,COMERCIALES,INDEPENDIENTES,Cliente Regular,19760719,2500.00,2500.00,20150701,PANAMA,PANAMA,Panama,20200511,20200511,22.75,77.25,3.0,ACTIVA,5457XXXXXXXX5006,45
556,2020-07-31,600220006,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,58565.76,2017-11-22,20471203.0,0.0,1. Al día,20201003.0,20201003.0,20200331.0,1.0,62100.00,58565.76,NaN,NaN,activo,NaN,Secundaria,MARRIED,MALE,2,-,AGRICULTURA AGRONOMIA,P Natural,PA,PA,22Y,AGRO,INDEPENDIENTES,Cliente Regular,19820326,1597.75,1597.75,20140101,PANAMA,CHIRIQUI,Panama,20200303,20200303,82.66,140.09,3.0,NaN,3030XXXX0780,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263234,2020-10-31,600060350,TDC,TDC,3182.02,2017-07-25,20210731.0,0.0,1. Al día,20201112.0,20201112.0,20200724.0,1.0,3095.98,210.97,NaN,NaN,activo,NaN,Universitario,MARRIED,FEMALE,0,-,CONSTRUCCION,P Natural,VE,PA,22Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19850523,2000.00,2000.00,20100102,PANAMA,PANAMA,PANAMA,20200213,20200304,62.97,174.00,3.0,INACT TEMPORAL,5436XXXXXXXX1007,40
263236,2020-10-31,600138744,TDC,TDC,4228.46,2017-07-24,20210731.0,0.0,1. Al día,20201112.0,20201112.0,20200813.0,3.0,2600.00,158.06,NaN,NaN,activo,NaN,Maestría,MARRIED,MALE,0,-,ADMINISTRACION,P Natural,PA,PA,9Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19641221,1000.00,1000.00,20090101,PANAMA,PANAMA,PANAMA,20200205,20191129,120.00,20.00,3.0,MOROSIDAD,5436XXXXXXXX6010,40
263237,2021-05-31,600190942,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,70110.75,2017-08-08,20470903.0,0.0,1. Al día,20210603.0,20210603.0,20200702.0,1.0,78302.00,261.71,NaN,NaN,activo,NaN,Universitario,SINGLE,MALE,0,-,ARQUITECTURA Y URBANISMO,P Natural,PA,PA,22Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19870714,1400.00,1400.00,20151001,PANAMA,PANAMA OESTE,LA CHORRERA,20210503,20210503,73.23,188.48,3.0,NaN,3030XXXX9533,47
263238,2021-05-31,600184221,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,92971.04,2017-08-31,20470903.0,0.0,1. Al día,20210603.0,20210603.0,20201215.0,1.0,97979.04,415.76,NaN,NaN,activo,NaN,Universitario,SINGLE,MALE,2,-,ADMINISTRACION,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19780508,6570.84,6570.84,20130101,PANAMA,PANAMA,PANAMA,20210503,20200317,415.76,4.94,3.0,NaN,3030XXXX9800,46
263239,2021-05-31,600127559,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,41523.15,2017-10-06,20471103.0,0.0,1. Al día,20210603.0,20210603.0,20200702.0,1.0,45000.00,153.66,NaN,NaN,activo,NaN,Universitario,SINGLE,MALE,0,-,ADMINISTRACION,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19810604,6546.93,6546.93,20060130,PANAMA,VERAGUAS,SANTIAGO,20210503,20210503,48.57,105.09,3.0,NaN,3030XXXX0183,45
263240,2021-06-30,600136794,CONSUMO PERSONAL,Gob. Administrativo,4541.99,2013-11-29,20241103.0,0.0,1. Al día,20210729.0,20210729.0,20210330.0,1.0,8300.00,117.15,NaN,NaN,activo,NaN,Maestría,MARRIED,FEMALE,0,-,AGRICULTURA AGRONOMIA,P Natural,PA,PA,9Y,AGRO,INDEPENDIENTES,Cliente Regular,19810630,700.00,700.00,20160101,PANAMA,PANAMA,PANAMA,20210629,20210629,52.45,63.24,3.0,NaN,3230XXXX9515,93
263242,2021-11-30,600163086,CONSUMO PERSONAL,PP Readecuación de Préstamo,15867.19,2020-07-21,20530203.0,0.0,1. Al día,20211203.0,20211203.0,20200721.0,1.0,16460.00,160.81,0.0,NaN,activo,NaN,Post-Grado,MARRIED,FEMALE,1,GERENTE SUB GERENTE,SERVICIO DE CONSULTORIA,P Natural,VE,PA,7Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19810512,3750.00,3750.00,20150601,PANAMA,PANAMA,Panama,20211103,20210111,160.81,360.00,2.0,NaN,1020XXX862,17
263243,2021-11-30,600051362,CONSUMO PERSONAL,Consumo Garantía Hip.,115000.00,2020-07-23,20350803.0,0.0,1. Al día,20211203.0,20211203.0,20210601.0,1.0,115000.00,985.22,0.0,NaN,activo,NaN,Universitario,SINGLE,MALE,0,GERENTE SUB GERENTE,MECANICA Y RESPUESTOS,Persona Juridica,PA,PA,7Y,COMERCIALES,INDEPENDIENTES,Cliente Regular,19550922,9931.25,9931.25,20080401,PANAMA,PANAMA,Panama,20211103,NaN,985.22,0.00,3.0,NaN,1020XXX876,17
263250,2022-02-28,600201762,CONSUMO PERSONAL,PP Readecuación de Préstamo,22045.23,2021-09-06,20360303.0,23.0,2. Hasta 30 días,20220303.0,20220303.0,20210906.0,3.0,22040.00,280.00,0.0,NaN,activo,NaN,Universitario,SINGLE,MALE,0,-,ADMINISTRACION,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19870306,6000.00,6000.00,20040101,PANAMA,CHIRIQUI,DAVID,NaN,NaN,0.00,0.00,3.0,NaN,1021XXX152,6
263252,2022-02-28,600035268,CONSUMO PERSONAL,PP Readecuación de Préstamo,11613.07,2021-09-06,20501103.0,0.0,1. Al día,20220303.0,20220303.0,20210906.0,3.0,11560.00,112.00,0.0,NaN,activo,NaN,Universitario,MARRIED,MALE,0,-,ROPA CALZADO Y ACCESORIOS,P Natural,PA,PA,7Y,COMERCIALES,INDEPENDIENTES,Cliente Regular,19630601,753.65,753.65,20150406,PANAMA,COCLE,NATA,20220221,NaN,55.75,0.00,3.0,NaN,1021XXX586,6
263253,2022-02-28,600037203,CONSUMO PERSONAL,PP Readecuación de Préstamo,39584.65,2021-09-06,20440903.0,0.0,1. Al día,20220303.0,20220303.0,20210906.0,3.0,39590.00,407.00,0.0,NaN,activo,NaN,Universitario,MARRIED,MALE,0,-,ADMINISTRACION,P Natural,IN,PA,13Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19651223,11000.00,11000.00,19891204,PANAMA,PANAMA,SAN MIGUELITO,20220203,20211203,311.62,82.28,3.0,NaN,1021XXX632,6
263254,2022-02-28,600249181,CONSUMO PERSONAL,PP Readecuación de Préstamo,51440.52,2021-09-06,20500503.0,0.0,1. Al día,20220303.0,20220303.0,20220218.0,3.0,51150.00,635.00,0.0,NaN,activo,NaN,Universitario,SINGLE,MALE,0,GERENTE SUB GERENTE,CONSTRUCCION,P Natural,PA,PA,22Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19790624,2735.19,2735.19,20180101,PANAMA,PANAMA,Panama,NaN,20220217,0.00,31.75,3.0,NaN,1021XXX667,6
263260,2022-06-30,600228166,CONSUMO PERSONAL,PP Readecuación de Préstamo,12445.98,2021-04-19,20310803.0,0.0,1. Al día,20220703.0,20220703.0,20210419.0,1.0,13250.00,199.00,0.0,NaN,activo,NaN,Post-Grado,MARRIED,FEMALE,1,-,PUBLICIDAD Y MERCADEO,P Natural,PA,PA,5Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19850918,1930.54,1930.54,20150801,PANAMA,CHIRIQUI,DOLEGA,20220603,20220603,97.10,82.76,2.0,NaN,1020XXX467,15
263261,2022-06-30,600223335,CONSUMO PERSONAL,PP Readecuación de Préstamo,6047.06,2021-04-19,20310303.0,0.0,1. Al día,20220703.0,20220703.0,20210419.0,1.0,6380.00,100.00,0.0,NaN,activo,NaN,Maestría,MARRIED,FEMALE,1,-,ADMINISTRACION,P Natural,CO,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19910119,2000.00,2000.00,20130315,PANAMA,PANAMA,Panama,20220603,20220603,47.20,43.54,2.0,NaN,1020XXX777,15
263263,2022-06-30,600192173,CONSUMO PERSONAL,PP Readecuación de Préstamo,16284.93,2021-04-19,20331103.0,0.0,1. Al día,20220703.0,20220703.0,20210419.0,1.0,17620.00,250.00,0.0,NaN,activo,NaN,Universitario,SINGLE,MALE,3,AGENTE DE SEGUROS,PUERTOS Y ADUANAS,P Natural,PA,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19720115,5000.00,5000.00,20081003,PANAMA,PANAMA,-,20220606,20220606,141.03,9.52,2.0,NaN,1020XXX878,15
263277,2020-11-30,800029619,TDC,TDC,32606.40,2019-04-15,20220430.0,0.0,1. Al día,20201214.0,20201214.0,20200724.0,1.0,29320.89,4320.61,NaN,NaN,activo,NaN,Universitario,SINGLE,FEMALE,0,ADMINISTRADOR,ADMINISTRACION,P Natural,VE,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19750811,20142.02,20142.02,20170829,PANAMA,PANAMA,Panama,20200328,20200328,424.29,175.71,3.0,SOBREGIRADA,5270XXXXXXXX2003,20
263278,2020-11-30,800043619,TDC,TDC,8988.39,2017-05-24,20210531.0,0.0,1. Al día,20201214.0,20201214.0,20200724.0,1.0,8011.44,1265.06,NaN,NaN,activo,NaN,Universitario,SINGLE,MALE,1,-,PUBLICIDAD Y MERCADEO,P Natural,VE,PA,22Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19820707,1812.83,1812.83,20120701,PANAMA,PANAMA,PANAMA,20200303,20200303,128.50,133.98,3.0,INACT TEMPORAL,5270XXXXXXXX4016,43
263280,2020-11-30,600080325,TDC,TDC,11058.99,2017-10-07,20210430.0,0.0,1. Al día,20201214.0,20201214.0,20200812.0,1.0,10840.00,588.00,NaN,NaN,activo,NaN,Técnico,SINGLE,MALE,0,DIRECTOR,CONSTRUCCION,P Natural,VE,PA,11Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19571211,3000.00,3000.00,20160101,PANAMA,PANAMA,-,20200222,20201103,161.97,205.00,3.0,ACTIVA,5270XXXXXXXX4003,39

In [32]:
Base_Independientes_f['mes']= Base_Independientes_f['FECHA'].dt.to_period('M')
Base_Independientes_f['mes_inicio']= Base_Independientes_f['FECHA_INICIO'].dt.to_period('M')

max_morosidad_cliente = Base_Independientes_f.groupby(['mes','CLIENTE'])['DIAS_MORA'].agg({"max"}).reset_index()
max_morosidad_cliente

            mes    CLIENTE   max
0       2017-01        142   0.0
1       2017-01      14052   0.0
2       2017-01      31180   0.0
3       2017-01    2227129  26.0
4       2017-01  200111260   0.0
5       2017-01  200194137   0.0
6       2017-01  200202823   0.0
7       2017-01  201421604   0.0
8       2017-01  201442214   0.0
9       2017-01  201476823   0.0
10      2017-01  201604443   0.0
11      2017-01  201894919   0.0
12      2017-01  201955981   0.0
13      2017-01  202347274   0.0
14      2017-01  202909805   0.0
15      2017-01  204018404   0.0
16      2017-01  204473030   0.0
17      2017-01  205465792   0.0
18      2017-01  600000008   0.0
19      2017-01  600000034   0.0
20      2017-01  600000083   0.0
21      2017-01  600000084   0.0
22      2017-01  600000125   0.0
23      2017-01  600000267  28.0
24      2017-01  600000358   0.0
25      2017-01  600000430   0.0
26      2017-01  600000692   0.0
27      2017-01  600000719   0.0
28      2017-01  600000750   0.0
29      2017-01  600000781   0.0
...         ...        ...   ...
183669  2022-07  990105220   0.0
183670  2022-07  990105314   0.0
183671  2022-07  990105317   0.0
183672  2022-07  990105343   0.0
183673  2022-07  990105426   0.0
183674  2022-07  990105540   0.0
183675  2022-07  990105800   0.0
183676  2022-07  990105854   0.0
183677  2022-07  990105881   0.0
183678  2022-07  990105882   0.0
183679  2022-07  990105951   0.0
183680  2022-07  990105972   0.0
183681  2022-07  990105977   0.0
183682  2022-07  990105990   0.0
183683  2022-07  990105994   0.0
183684  2022-07  990106019   0.0
183685  2022-07  990106158   0.0
183686  2022-07  990106231   0.0
183687  2022-07  990106234   0.0
183688  2022-07  990106261   0.0
183689  2022-07  990106268   0.0
183690  2022-07  990106270   0.0
183691  2022-07  990106298   0.0
183692  2022-07  990106326   0.0
183693  2022-07  990106345   0.0
183694  2022-07  990106349   0.0
183695  2022-07  990106369   0.0
183696  2022-07  990106390   0.0
183697  2022-07  990106420   0.0
183698  2022-07  990106436   0.0

[183699 rows x 3 columns]

In [33]:
max_morosidad_cliente[max_morosidad_cliente.CLIENTE == 600007221]

            mes    CLIENTE    max
59      2017-01  600007221    0.0
1958    2017-02  600007221    0.0
3914    2017-03  600007221    0.0
5956    2017-04  600007221    0.0
8078    2017-05  600007221    0.0
10235   2017-06  600007221    0.0
12484   2017-07  600007221    0.0
14801   2017-08  600007221    0.0
17208   2017-09  600007221    0.0
19684   2017-10  600007221    0.0
22230   2017-11  600007221    0.0
24852   2017-12  600007221    0.0
27522   2018-01  600007221    0.0
30200   2018-02  600007221    0.0
32919   2018-03  600007221    0.0
35692   2018-04  600007221    0.0
38547   2018-05  600007221    0.0
41413   2018-06  600007221    0.0
44317   2018-07  600007221    0.0
47257   2018-08  600007221    0.0
50193   2018-09  600007221    0.0
53131   2018-10  600007221   26.0
56046   2018-11  600007221    0.0
58990   2018-12  600007221    0.0
61944   2019-01  600007221    0.0
64862   2019-02  600007221    0.0
67763   2019-03  600007221    0.0
70664   2019-04  600007221    0.0
73574   2019-05  600007221    0.0
76487   2019-06  600007221    0.0
...         ...        ...    ...
99454   2020-02  600007221   53.0
102225  2020-03  600007221    0.0
104964  2020-04  600007221    0.0
107683  2020-05  600007221    0.0
110381  2020-06  600007221    0.0
113070  2020-07  600007221    0.0
115722  2020-08  600007221    0.0
118326  2020-09  600007221    0.0
120922  2020-10  600007221    0.0
123509  2020-11  600007221    0.0
126068  2020-12  600007221    0.0
128632  2021-01  600007221    0.0
131175  2021-02  600007221    0.0
133734  2021-03  600007221    0.0
136289  2021-04  600007221    0.0
138872  2021-05  600007221    0.0
141498  2021-06  600007221    0.0
144150  2021-07  600007221    0.0
146830  2021-08  600007221    0.0
149546  2021-09  600007221    0.0
152318  2021-10  600007221    0.0
155162  2021-11  600007221    0.0
158045  2021-12  600007221    0.0
160970  2022-01  600007221   20.0
163954  2022-02  600007221   48.0
167024  2022-03  600007221   79.0
170166  2022-04  600007221  109.0
173400  2022-05  600007221  140.0
176737  2022-06  600007221  170.0
180199  2022-07  600007221  201.0

[67 rows x 3 columns]

In [34]:
len(Base_Independientes_f.Operacion_codificada.unique())

6065

In [35]:
len(Base_Independientes_f.CLIENTE.unique())

4896

In [36]:
#idx = np.random.permutation(np.arange(len(df)))

In [37]:
Base_Independientes_f.head()

,FECHA,CLIENTE,SECTOR1,SECTOR4,SALDO,FECHA_INICIO,FECHA_VENCIMIENTO,DIAS_MORA,RANGO_MORA,PROXIMO_PAGO_CAPITAL,PROXIMO_PAGO_INTERES,fecha_reestructurado,clasificacion_Regulatoria,MONTO_IN,CUOTA_XPAGAR,ingreso,segmento,cartera,max_mora_ult_12M,Descripcion_Nivel_Educacion,Estadocivil,Genero,cantidad_Dependientes,Cargo,DescripcionIndustria,DescripcionSector,Nacionalidad,Residencia,TiempoRelacionBanco,CLASIFICACION_4,CLASIFICACION_5,SubTipoCliente,FechaNacimiento,Imgreso_DIMCLIENTES,IngresoMensual,FechaEmpleoActual,pais,provincia,ciudad,Fecha_Ult_pago_Interes,Fecha_Ult_pago_Capital,Monto_Ult_pago_Interes,Monto_Ult_pago_Capital,categoria_cambio,DESC_ESTADO_TARJETA_t,Operacion_codificada,MADUREZ,mes,mes_inicio
0,2022-02-28,600127517,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,71103.62,2014-09-25,20440903.0,0.0,1. Al día,20220303.0,20220303.0,NaN,1.0,80410.0,389.94,0.0,NaN,activo,NaN,Universitario,MARRIED,MALE,0,ABOGADO,LEGAL,P Natural,PA,PA,9Y,SERVICIOS,INDEPENDIENTES,Cliente Regular,19740108,2530.83,2530.83,20050301,PANAMA,PANAMA,PANAMA,20220210,20220210,321.70,19.50,NaN,NaN,3030XXXX5646,91,2022-02,2014-09
1,2022-02-28,600086511,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,97427.19,2014-10-21,20441003.0,0.0,1. Al día,20220303.0,20220303.0,20210602.0,3.0,106500.0,498.58,0.0,NaN,activo,NaN,Maestría,MARRIED,MALE,0,-,CONSTRUCCION,P Natural,PA,PA,11Y,CONSTRUCCION,INDEPENDIENTES,Cliente Regular,19820901,5000.00,5000.00,20151101,PANAMA,PANAMA,PANAMA,20200317,20201126,304.79,332.93,3.0,NaN,3030XXXX6075,90,2022-02,2014-10
2,2022-02-28,600114703,HIPOTECA RESIDENCIAL,Hipoteca Preferencial,65146.81,2014-10-30,20441003.0,0.0,1. Al día,20220303.0,20220303.0,NaN,1.0,73000.0,199.73,0.0,NaN,activo,NaN,Universitario,SINGLE,FEMALE,0,-,ROPA CALZADO Y ACCESORIOS,P Natural,PA,PA,22Y,COMERCIALES,INDEPENDIENTES,Cliente Regular,19790620,2000.00,2000.00,20090301,PANAMA,CHIRIQUI,DAVID,20220203,20220203,144.99,18.16,NaN,NaN,3030XXXX6155,90,2022-02,2014-10
3,2022-03-31,990052433,HIPOTECA RESIDENCIAL,Hipoteca No Preferencial,300800.00,2022-03-18,20520403.0,0.0,1. Al día,20220503.0,20220503.0,NaN,1.0,300800.0,777.27,0.0,NaN,activo,NaN,Doctorado,MARRIED,MALE,0,ADMINISTRADOR,ALIMENTOS,P Natural,VE,PA,1Y,COMERCIALES,INDEPENDIENTES,Cliente Regular,19760906,5735.00,5735.00,20191204,PANAMA,PANAMA,Panama,NaN,NaN,0.00,0.00,NaN,NaN,1021XXX807,1,2022-03,2022-03
4,2022-03-31,600044329,CONSUMO PERSONAL,PP Prendarios,52202.00,2022-03-19,20270319.0,0.0,1. Al día,20270319.0,20220419.0,NaN,1.0,52202.0,52202.00,0.0,NaN,activo,NaN,Doctorado,MARRIED,FEMALE,1,ABOGADO,INSTITUCIONES DE GOBIERNO,P Natural,PA,PA,22Y,OTROS,INDEPENDIENTES,Cliente Regular,19770613,14113.75,14113.75,20191023,PANAMA,PANAMA,Panama,NaN,NaN,0.00,0.00,NaN,NaN,1021XXX567,1,2022-03,2022-03

# FILTRAR POR TDC Y CONSUMO PERSONAL

In [38]:
filtro2 = (Base_Independientes_f['SECTOR1'] == 'TDC') |  (Base_Independientes_f['SECTOR1'] == 'CONSUMO PERSONAL')

In [39]:
Base_Independientes_ff = Base_Independientes_f[filtro2]

In [40]:
Base_Independientes_ff.SECTOR1.value_counts()

TDC                 181427
CONSUMO PERSONAL     33728
Name: SECTOR1, dtype: int64

In [41]:
Operaciones = Base_Independientes_ff.drop_duplicates(subset =['CLIENTE','mes_inicio'])
Operaciones = Operaciones[['CLIENTE','mes_inicio']]
Operaciones.head()

      CLIENTE mes_inicio
4   600044329    2022-03
8   600200013    2022-03
12  600245927    2021-05
13  600221759    2021-05
14  600212438    2017-11

In [42]:
Operaciones[Operaciones.CLIENTE == 600072931 ].head()

         CLIENTE mes_inicio
1030   600072931    2017-09
10544  600072931    2021-09
12419  600072931    2019-04
21372  600072931    2019-01
45690  600072931    2020-06

In [43]:
len(Operaciones.CLIENTE.unique())

4593

In [44]:
len(max_morosidad_cliente.CLIENTE.unique())

4896

In [45]:
Operaciones.head()

      CLIENTE mes_inicio
4   600044329    2022-03
8   600200013    2022-03
12  600245927    2021-05
13  600221759    2021-05
14  600212438    2017-11

In [46]:
max_morosidad_cliente.head()

       mes    CLIENTE   max
0  2017-01        142   0.0
1  2017-01      14052   0.0
2  2017-01      31180   0.0
3  2017-01    2227129  26.0
4  2017-01  200111260   0.0

# INNER JOIN

# MES DE CIERRE MENOR A 12 MESES DE MES DE INICIO

In [47]:
base_objetivo = max_morosidad_cliente.merge(Operaciones, on='CLIENTE', how='inner')
base_objetivo.head()

       mes  CLIENTE   max mes_inicio
0  2017-01      142   0.0    2010-08
1  2017-01      142   0.0    2016-09
2  2017-02      142   0.0    2010-08
3  2017-02      142   0.0    2016-09
4  2017-03      142  26.0    2010-08

PRIMERO FILTRO MES CIERRE MENOR A 12 MESES
SEGUNDO AGRUPO POR CLIENTE MES INICIO PARA OBTENER LA MAX MOROSIDAD ULT 12M

# MES DE CIERRE MENOR A 12 MESES DE MES DE INICIO

In [48]:
base_objetivo.isna().sum()

mes           0
CLIENTE       0
max           0
mes_inicio    0
dtype: int64

In [49]:
len(base_objetivo)

379132

In [50]:
len(base_objetivo.CLIENTE.unique())

4593

In [51]:
#base_objetivo['mes_inicio']= base_objetivo['FECHA_INICIO'].dt.to_period('M')

In [52]:
base_objetivo.head()

       mes  CLIENTE   max mes_inicio
0  2017-01      142   0.0    2010-08
1  2017-01      142   0.0    2016-09
2  2017-02      142   0.0    2010-08
3  2017-02      142   0.0    2016-09
4  2017-03      142  26.0    2010-08

In [53]:
base_objetivo = base_objetivo[base_objetivo.mes_inicio<=base_objetivo.mes]

In [54]:
len(base_objetivo)

283520

In [55]:
len(base_objetivo.CLIENTE.unique())

4593

In [56]:
#base_objetivo['madurez'] = base_objetivo['mes'] - base_objetivo['mes_inicio']
#base_objetivo['madurez'] = base_objetivo['madurez'].apply(lambda x: x.n)

In [57]:
len(base_objetivo)

283520

In [58]:
#base_objetivo = base_objetivo[base_objetivo.madurez<=12].reset_index(drop = True)

In [59]:
#base_objetivo.describe()

In [60]:
base_objetivo['Fecha_Mora30'] = base_objetivo['max'].apply(lambda x: 1 if x>=30 else None)
base_objetivo['Fecha_Mora60'] = base_objetivo['max'].apply(lambda x: 1 if x>=60 else None)
base_objetivo['Fecha_Mora90'] = base_objetivo['max'].apply(lambda x: 1 if x>=90 else None)

In [61]:
base_objetivo.describe()

            CLIENTE            max  Fecha_Mora30  Fecha_Mora60  Fecha_Mora90
count  2.835200e+05  283520.000000       23045.0       18424.0       15409.0
mean   6.149366e+08      17.282213           1.0           1.0           1.0
std    9.049889e+07      68.510447           0.0           0.0           0.0
min    1.420000e+02       0.000000           1.0           1.0           1.0
25%    6.000945e+08       0.000000           1.0           1.0           1.0
50%    6.001684e+08       0.000000           1.0           1.0           1.0
75%    6.002101e+08       0.000000           1.0           1.0           1.0
max    9.901064e+08    1184.000000           1.0           1.0           1.0

In [62]:
for i in base_objetivo.index:
    
    if base_objetivo.loc[i,'Fecha_Mora30'] == 1:
        base_objetivo.loc[i,'Fecha_Mora30'] = str(base_objetivo.loc[i,'mes'])[:4] + str(base_objetivo.loc[i,'mes'])[5:]
        base_objetivo.loc[i,'Fecha_Mora30'] = int ( base_objetivo.loc[i,'Fecha_Mora30'])

In [63]:
base_objetivo[base_objetivo.Fecha_Mora30.notnull()]

,mes,CLIENTE,max,mes_inicio,Fecha_Mora30,Fecha_Mora60,Fecha_Mora90
18,2017-12,142,47.0,2010-08,201712,NaN,NaN
19,2017-12,142,47.0,2016-09,201712,NaN,NaN
20,2018-01,142,77.0,2010-08,201801,1.0,NaN
21,2018-01,142,77.0,2016-09,201801,1.0,NaN
22,2018-02,142,104.0,2010-08,201802,1.0,1.0
23,2018-02,142,104.0,2016-09,201802,1.0,1.0
24,2018-03,142,137.0,2010-08,201803,1.0,1.0
25,2018-03,142,137.0,2016-09,201803,1.0,1.0
26,2018-04,142,166.0,2010-08,201804,1.0,1.0
27,2018-04,142,166.0,2016-09,201804,1.0,1.0
28,2018-05,142,197.0,2010-08,201805,1.0,1.0
29,2018-05,142,197.0,2016-09,201805,1.0,1.0
30,2018-06,142,226.0,2010-08,201806,1.0,1.0
31,2018-06,142,226.0,2016-09,201806,1.0,1.0
32,2018-07,142,257.0,2010-08,201807,1.0,1.0
33,2018-07,142,257.0,2016-09,201807,1.0,1.0
34,2018-08,142,287.0,2010-08,201808,1.0,1.0
35,2018-08,142,287.0,2016-09,201808,1.0,1.0
36,2018-09,142,316.0,2010-08,201809,1.0,1.0
37,2018-09,142,316.0,2016-09,201809,1.0,1.0
38,2018-10,142,347.0,2010-08,201810,1.0,1.0
39,2018-10,142,347.0,2016-09,201810,1.0,1.0
40,2018-11,142,376.0,2010-08,201811,1.0,1.0
41,2018-11,142,376.0,2016-09,201811,1.0,1.0
42,2018-12,142,407.0,2010-08,201812,1.0,1.0
43,2018-12,142,407.0,2016-09,201812,1.0,1.0
44,2019-01,142,407.0,2010-08,201901,1.0,1.0
45,2019-01,142,407.0,2016-09,201901,1.0,1.0
196,2019-07,31180,47.0,2009-09,201907,NaN,NaN
235,2017-05,2227129,86.0,2014-07,201705,1.0,NaN
...,...,...,...,...,...,...,...
372714,2022-02,990065930,109.0,2021-08,202202,1.0,1.0
372715,2022-03,990065930,140.0,2021-08,202203,1.0,1.0
372716,2022-04,990065930,170.0,2021-08,202204,1.0,1.0
372717,2022-05,990065930,201.0,2021-08,202205,1.0,1.0
372718,2022-06,990065930,231.0,2021-08,202206,1.0,1.0
372719,2022-07,990065930,262.0,2021-08,202207,1.0,1.0
372881,2022-05,990005694,58.0,2021-07,202205,NaN,NaN
372882,2022-06,990005694,88.0,2021-07,202206,1.0,NaN
372883,2022-07,990005694,118.0,2021-07,202207,1.0,1.0
373870,2021-10,990070045,49.0,2021-07,202110,NaN,NaN
373871,2021-11,990070045,79.0,2021-07,202111,1.0,NaN
373872,2021-12,990070045,110.0,2021-07,202112,1.0,1.0
373873,2022-01,990070045,141.0,2021-07,202201,1.0,1.0
373874,2022-02,990070045,169.0,2021-07,202202,1.0,1.0
373875,2022-03,990070045,200.0,2021-07,202203,1.0,1.0
373876,2022-04,990070045,230.0,2021-07,202204,1.0,1.0
373877,2022-05,990070045,261.0,2021-07,202205,1.0,1.0
373878,2022-06,990070045,291.0,2021-07,202206,1.0,1.0
373879,2022-07,990070045,322.0,2021-07,202207,1.0,1.0
374162,2022-07,600249459,57.0,2021-09,202207,NaN,NaN
374626,2022-07,990072757,57.0,2021-08,202207,NaN,NaN
374627,2022-07,990072757,57.0,2022-07,202207,NaN,NaN
375499,2022-06,990078123,58.0,2022-03,202206,NaN,NaN
375500,2022-06,990078123,58.0,2021-10,202206,NaN,NaN
375501,2022-07,990078123,88.0,2022-03,202207,1.0,NaN
375502,2022-07,990078123,88.0,2021-10,202207,1.0,NaN
376179,2022-06,990083842,50.0,2021-12,202206,NaN,NaN
376180,2022-07,990083842,81.0,2021-12,202207,1.0,NaN
376606,2022-06,990081241,50.0,2021-11,202206,NaN,NaN
376607,2022-07,990081241,81.0,2021-11,202207,1.0,NaN

In [64]:
for i in base_objetivo.index:
    
    if base_objetivo.loc[i,'Fecha_Mora60'] == 1:
        base_objetivo.loc[i,'Fecha_Mora60'] = str(base_objetivo.loc[i,'mes'])[:4] + str(base_objetivo.loc[i,'mes'])[5:]
        base_objetivo.loc[i,'Fecha_Mora60'] = int ( base_objetivo.loc[i,'Fecha_Mora60'])

In [65]:
for i in base_objetivo.index:
    
    if base_objetivo.loc[i,'Fecha_Mora90'] == 1:
        base_objetivo.loc[i,'Fecha_Mora90'] = str(base_objetivo.loc[i,'mes'])[:4] + str(base_objetivo.loc[i,'mes'])[5:]
        base_objetivo.loc[i,'Fecha_Mora90'] = int ( base_objetivo.loc[i,'Fecha_Mora90'])

# FECHA DE INICIO APARTIR DE LA PRIMERA PRIMERA FECHA DE CIERRE

# COLOCAR

In [66]:
base_objetivo= base_objetivo[base_objetivo.mes_inicio >= '2016-12']

In [67]:
base_objetivo[base_objetivo.Fecha_Mora90.notnull()].loc[:, base_objetivo.columns != 'madurez']

,mes,CLIENTE,max,mes_inicio,Fecha_Mora30,Fecha_Mora60,Fecha_Mora90
8343,2019-10,600004150,105.0,2017-02,201910,201910,201910
10029,2017-08,600006916,116.0,2017-03,201708,201708,201708
10032,2017-09,600006916,145.0,2017-03,201709,201709,201709
10035,2017-10,600006916,167.0,2017-03,201710,201710,201710
10038,2017-11,600006916,196.0,2017-03,201711,201711,201711
10041,2017-12,600006916,227.0,2017-03,201712,201712,201712
10044,2018-01,600006916,257.0,2017-03,201801,201801,201801
10047,2018-02,600006916,284.0,2017-03,201802,201802,201802
10050,2018-03,600006916,317.0,2017-03,201803,201803,201803
10053,2018-04,600006916,346.0,2017-03,201804,201804,201804
10056,2018-05,600006916,257.0,2017-03,201805,201805,201805
10059,2018-06,600006916,286.0,2017-03,201806,201806,201806
10062,2018-07,600006916,317.0,2017-03,201807,201807,201807
10065,2018-08,600006916,347.0,2017-03,201808,201808,201808
10068,2018-09,600006916,376.0,2017-03,201809,201809,201809
10470,2022-04,600007221,109.0,2021-05,202204,202204,202204
10471,2022-04,600007221,109.0,2017-06,202204,202204,202204
10472,2022-04,600007221,109.0,2022-04,202204,202204,202204
10474,2022-05,600007221,140.0,2021-05,202205,202205,202205
10475,2022-05,600007221,140.0,2017-06,202205,202205,202205
10476,2022-05,600007221,140.0,2022-04,202205,202205,202205
10478,2022-06,600007221,170.0,2021-05,202206,202206,202206
10479,2022-06,600007221,170.0,2017-06,202206,202206,202206
10480,2022-06,600007221,170.0,2022-04,202206,202206,202206
10482,2022-07,600007221,201.0,2021-05,202207,202207,202207
10483,2022-07,600007221,201.0,2017-06,202207,202207,202207
10484,2022-07,600007221,201.0,2022-04,202207,202207,202207
10685,2022-07,600007675,118.0,2021-03,202207,202207,202207
23347,2019-08,600021824,107.0,2017-11,201908,201908,201908
23350,2019-09,600021824,136.0,2017-11,201909,201909,201909
...,...,...,...,...,...,...,...
372056,2022-03,600264110,209.0,2021-06,202203,202203,202203
372057,2022-04,600264110,239.0,2021-06,202204,202204,202204
372058,2022-05,600264110,270.0,2021-06,202205,202205,202205
372059,2022-06,600264110,300.0,2021-06,202206,202206,202206
372060,2022-07,600264110,330.0,2021-06,202207,202207,202207
372452,2021-10,990061883,112.0,2021-05,202110,202110,202110
372453,2021-11,990061883,142.0,2021-05,202111,202111,202111
372454,2021-12,990061883,173.0,2021-05,202112,202112,202112
372455,2022-01,990061883,204.0,2021-05,202201,202201,202201
372456,2022-02,990061883,232.0,2021-05,202202,202202,202202
372457,2022-03,990061883,263.0,2021-05,202203,202203,202203
372458,2022-04,990061883,293.0,2021-05,202204,202204,202204
372459,2022-05,990061883,324.0,2021-05,202205,202205,202205
372460,2022-06,990061883,354.0,2021-05,202206,202206,202206
372461,2022-07,990061883,385.0,2021-05,202207,202207,202207
372714,2022-02,990065930,109.0,2021-08,202202,202202,202202
372715,2022-03,990065930,140.0,2021-08,202203,202203,202203
372716,2022-04,990065930,170.0,2021-08,202204,202204,202204
372717,2022-05,990065930,201.0,2021-08,202205,202205,202205
372718,2022-06,990065930,231.0,2021-08,202206,202206,202206
372719,2022-07,990065930,262.0,2021-08,202207,202207,202207
372883,2022-07,990005694,118.0,2021-07,202207,202207,202207
373872,2021-12,990070045,110.0,2021-07,202112,202112,202112
373873,2022-01,990070045,141.0,2021-07,202201,202201,202201
373874,2022-02,990070045,169.0,2021-07,202202,202202,202202
373875,2022-03,990070045,200.0,2021-07,202203,202203,202203
373876,2022-04,990070045,230.0,2021-07,202204,202204,202204
373877,2022-05,990070045,261.0,2021-07,202205,202205,202205
373878,2022-06,990070045,291.0,2021-07,202206,202206,202206
373879,2022-07,990070045,322.0,2021-07,202207,202207,202207

In [68]:
fecha_mora_operacion = base_objetivo.groupby(['CLIENTE','mes_inicio'])['Fecha_Mora30','Fecha_Mora60','Fecha_Mora90'].agg({"min"}).reset_index()
fecha_mora_operacion.head()

     CLIENTE mes_inicio Fecha_Mora30 Fecha_Mora60 Fecha_Mora90
                                 min          min          min
0      14052    2019-03          NaN          NaN          NaN
1  200111260    2018-05          NaN          NaN          NaN
2  200194137    2018-01          NaN          NaN          NaN
3  200194137    2019-06          NaN          NaN          NaN
4  200202823    2017-06          NaN          NaN          NaN

In [69]:
fecha_mora_operacion[fecha_mora_operacion['Fecha_Mora90']['min'].notnull()]

        CLIENTE mes_inicio Fecha_Mora30 Fecha_Mora60 Fecha_Mora90
                                    min          min          min
57    600001014    2017-03     201809.0     201810.0     201811.0
78    600002522    2017-02     201807.0     201808.0     201809.0
80    600002751    2017-08     201810.0     201906.0     201907.0
90    600004150    2017-02     201811.0     201812.0     201910.0
112   600006916    2017-03     201706.0     201707.0     201708.0
115   600007221    2017-06     202002.0     202203.0     202204.0
116   600007221    2021-05     202202.0     202203.0     202204.0
117   600007221    2022-04     202204.0     202204.0     202204.0
120   600007675    2021-03     202205.0     202206.0     202207.0
125   600007740    2017-03     201711.0     201712.0     201801.0
243   600021824    2017-11     201906.0     201907.0     201908.0
251   600022213    2019-09     202001.0     202002.0     202003.0
260   600022827    2017-02     202112.0     202201.0     202202.0
261   600022827    2021-03     202112.0     202201.0     202202.0
264   600023388    2019-06     202107.0     202108.0     202109.0
265   600023388    2019-10     202107.0     202108.0     202109.0
266   600023388    2021-05     202107.0     202108.0     202109.0
267   600023388    2021-10     202110.0     202110.0     202110.0
280   600024956    2018-04     201904.0     201906.0     201907.0
281   600024956    2019-09     202204.0     202205.0     202206.0
288   600026532    2017-05     201806.0     201809.0     201810.0
289   600026532    2018-01     201806.0     201809.0     201810.0
308   600028934    2017-07     202103.0     202103.0     202103.0
368   600033432    2018-01     201805.0     201806.0     201807.0
372   600033874    2017-02     201710.0     201711.0     201712.0
375   600034105    2017-08     201809.0     201810.0     201811.0
384   600034994    2017-08     201801.0     201802.0     201803.0
416   600037302    2017-07     201907.0     201908.0     201909.0
427   600038087    2019-05     201911.0     202006.0     202006.0
449   600039516    2017-06     201804.0     201811.0     201812.0
...         ...        ...          ...          ...          ...
4746  800047624    2018-04     201807.0     201906.0     201907.0
4758  800063444    2016-12     201805.0     201806.0     201807.0
4760  800066083    2017-05     202203.0     202204.0     202205.0
4761  800066083    2021-05     202203.0     202204.0     202205.0
4762  800066083    2021-12     202203.0     202204.0     202205.0
4763  800066083    2022-01     202203.0     202204.0     202205.0
4771  800075733    2018-03     201909.0     201910.0     201911.0
4806  800097252    2017-10     201808.0     201810.0     201811.0
4830  800103797    2017-08     202204.0     202205.0     202206.0
4831  800103797    2018-05     202204.0     202205.0     202206.0
4832  800103797    2019-03     202204.0     202205.0     202206.0
4833  800103797    2021-04     202204.0     202205.0     202206.0
4834  800103797    2021-05     202204.0     202205.0     202206.0
4835  800103797    2022-02     202204.0     202205.0     202206.0
4836  800103797    2022-04     202204.0     202205.0     202206.0
4842  800105871    2017-08     201901.0     201902.0     201903.0
4843  800106559    2017-02     201806.0     201807.0     201808.0
4847  800107230    2017-09     201908.0     202001.0     202002.0
4926  990002966    2019-08     202204.0     202205.0     202206.0
4929  990003034    2021-01     202105.0     202106.0     202107.0
4930  990003037    2019-08     201912.0     202001.0     202002.0
4952  990005694    2021-07     202205.0     202206.0     202207.0
4974  990008063    2021-04     202108.0     202109.0     202110.0
5204  990046588    2021-01     202108.0     202109.0     202110.0
5233  990050000    2021-02     202202.0     202203.0     202204.0
5234  990050000    2021-05     202202.0     202203.0     202204.0
5355  990059289    2021-05     202109.0     202110.0     202111.0
5380  990061883    2021-05     202108.0     202109.0     202110.0
5440  990065930    2021-08     202112.0     202201.0     202202.0
5509  990070045    2021-07     202110.0     202111.0     202112.0

[807 rows x 5 columns]

In [70]:
fecha_mora_operacion.columns =fecha_mora_operacion.columns.droplevel(1)

In [71]:
fecha_mora_operacion.head()

     CLIENTE mes_inicio  Fecha_Mora30  Fecha_Mora60  Fecha_Mora90
0      14052    2019-03           NaN           NaN           NaN
1  200111260    2018-05           NaN           NaN           NaN
2  200194137    2018-01           NaN           NaN           NaN
3  200194137    2019-06           NaN           NaN           NaN
4  200202823    2017-06           NaN           NaN           NaN

In [72]:
fecha_mora_operacion.to_csv('../data/interim/base_final_mora.csv')